### ISSUE TITLE
Robust practice

### ISSUE THREAD

**Issue by ranska** [emiraydin/p2k#1]
You probably should add some cucumber test just to ensure that your app is stable
- test it with ci like (travis or semphore, circle ci), that will help other people to help you.

**Comment by emiraydin** [comment]
Thanks @ranska, I did consider writing BDD tests but skipped for faster prototyping at the time and forgot to add them later. I think I'll write the tests, thanks for reminding me :) As for doing continuous integration, I'm sure it will be beneficial as more people start contributing.
