### ISSUE TITLE
Cannot access p2k account

### ISSUE THREAD

**Issue by aecepoglu** [emiraydin/p2k#15]
When I go to p2k.co, I am redirected to https://p2k.co/plan/choose

When I enter my email address that I previously signed up with, it gives me a warning saying that email address exists.

Because of this, I cannot edit my deliveries.

**Comment by emiraydin** [comment]
You probably changed your username and that's why this is happening. Please send these product inquiries through Questions & Concerns button on bottom right of the website, happy to help.

**Comment by elzorrorebelde** [comment]
I'm getting this right now, why don't enable a sign-in page or something?
