### ISSUE TITLE
fail with better error message if payload is too large for Amazon

### ISSUE THREAD

**Issue by HarlanH** [emiraydin/p2k#3]
Hi, I'm using your hosted service. So far it's worked once, but currently I get an error:

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```

I'm attempting to send the latest 20 articles. Oh, I just tried a time-limited bucket of articles, and it worked. I wonder if I hit a capacity limit somewhere? Anyway, there's a bug. I'm happy to provide additional information if I can! Thanks.

**Comment by emiraydin** [comment]
@HarlanH Does it work with smaller number of articles in the 'latest articles' option? There is a 25MB file size limit for files you can send to Amazon devices (via email), so if your packaged articles with all the images exceed that, you might be having problems. And I'll keep that in mind to estimate such possibility better.

**Comment by HarlanH** [comment]
Ah, that does seem to work. I just sent 10 articles and it seemed to work without a problem. 

So, the issue is that it should fail with a nicer error message. Thank you!

**Comment by Wiltons** [comment]
Came here with this issue too, but I see it's already listed. Awesome app :+1:
